### ISSUE TITLE
How about ECC support and hammer test?

### ISSUE THREAD

**Issue by daiaji** [anphsw/memtest86-#25]
https://www.memtest86.com/ecc.htm

https://github.com/google/rowhammer-test

This is still very useful for verifying that ECC memory is working properly after purchase.

In addition, it should be very useful to write logs to the storage media to help locate memory errors after the PC is down for memtest.

**Comment by anphsw** [comment]
Rowhammer is already implemented in test set.
ECC memory is supported and simple errors is logged. But for now you cannot detect single-bit errors.
Since memtest86 is filesystem-unaware (it can be run from pxe or even bios code), writing logs is possible via serial console.
Writing to usb/sata media will include whole USB or sata support layer and filesystem layer (and this is huge abount of code). Better to use serial logger for this operation.
